### PR TITLE
Ft notifications 151208550

### PR DESCRIPTION
**Pull request by QUDUSKUNLE**
What does this PR do?

It adds Notification (In-App, SMS, Email) feature to the app.
Description of Task to be completed?

Integrate Notification(In-App, SMS, Email) system for the app.
How should this be manually tested?

An authenticated user can test it by placing an order.
Any background context you want to provide?

End to end testing

What are the relevant pivotal tracker stories?

#151208550

Screenshots (if appropriate)

screen shot 2017-10-04 at 1 25 26 am

screen shot 2017-10-04 at 1 43 40 am

screen shot 2017-10-04 at 1 45 50 am

screen shot 2017-10-04 at 1 48 21 am

### CODE REVIEW

**Review by THEozmic — APPROVED** [review]
GTM

**Review by THEozmic — CHANGES_REQUESTED** [review]
NGTM

**Review by johadi — APPROVED** [review]
GTM

**Review by THEozmic — APPROVED** [review]
GTM

**Pull request merged**
